# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hsar_cpp_arma <- function(X, y, W, M, Z, detval, detvalM, Unum, burnin, Nsim, thinning, rho_start, lambda_start, sigma2e_start, sigma2u_start, betas_start, Durbin) {
    .Call(`_HSAR_hsar_cpp_arma`, X, y, W, M, Z, detval, detvalM, Unum, burnin, Nsim, thinning, rho_start, lambda_start, sigma2e_start, sigma2u_start, betas_start, Durbin)
}

hsar_cpp_arma_lambda_0 <- function(X, y, W, Z, detval, Unum, burnin, Nsim, thinning, rho_start, sigma2e_start, sigma2u_start, betas_start, Durbin) {
    .Call(`_HSAR_hsar_cpp_arma_lambda_0`, X, y, W, Z, detval, Unum, burnin, Nsim, thinning, rho_start, sigma2e_start, sigma2u_start, betas_start, Durbin)
}

hsar_cpp_arma_rho_0 <- function(X, y, M, Z, detvalM, Unum, burnin, Nsim, thinning, lambda_start, sigma2e_start, sigma2u_start, betas_start) {
    .Call(`_HSAR_hsar_cpp_arma_rho_0`, X, y, M, Z, detvalM, Unum, burnin, Nsim, thinning, lambda_start, sigma2e_start, sigma2u_start, betas_start)
}

impact_cpp_arma <- function(betas, rhos, W) {
    .Call(`_HSAR_impact_cpp_arma`, betas, rhos, W)
}

impact_Durbin_cpp_arma <- function(betas, thetas, rhos, W) {
    .Call(`_HSAR_impact_Durbin_cpp_arma`, betas, thetas, rhos, W)
}

sar_cpp_arma <- function(X, y, W, detval, burnin, Nsim, thinning, rho_start, sigma2e_start, betas_start, Durbin) {
    .Call(`_HSAR_sar_cpp_arma`, X, y, W, detval, burnin, Nsim, thinning, rho_start, sigma2e_start, betas_start, Durbin)
}

